/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import daylamotpackage.Essay;
import daylamotpackage.MultipleChoiceQuestion;
import daylamotpackage.Subject;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class MainMenu extends javax.swing.JFrame {

    private DefaultListModel modelListSubject;
    private DefaultListModel modelListChapter;
    private DefaultListModel modelListAnswer;
    private DefaultComboBoxModel modelComboBox;
    private ArrayList<Subject> listSubject;
    private ArrayList<MultipleChoiceQuestion> listMultipleChoiceQuestion;
    private ArrayList<Integer> chapter;
    private ArrayList<Essay> essay;
    
    private boolean clickAddSubject;
    private int selectedIndex;
    private String subjectChoosen;
    private boolean chooseMultiChoiceQuestion;
    private boolean chooseEssay;
            

    public MainMenu() {
        initComponents();
        
        this.setResizable(false);
        
        // Subjects tab init
        this.tfCodeSubject.setEnabled(false);
        this.tfNameSubject.setEnabled(false);
        this.spNumberChapter.setEnabled(false);
        this.taOverview.setEnabled(false);
        this.btSave.setEnabled(false);

        this.listSubject = new ArrayList<>();
        this.btDeleteSubject.setEnabled(false);
        this.clickAddSubject = false;
        this.lbThongBao.setVisible(false);
        this.lbThongBaoCodeSubject.setVisible(false);
        this.lbThongBaoNameSubject.setVisible(false);
    
        
        
        // Question tab init
        this.lbTbDienCauHoi.setVisible(false);
        this.taBarem.setEnabled(false);
        this.taNoiDungCauHoi.setEnabled(false);
        this.jlistChuong.setVisible(false);
        this.jlistAnswer.setVisible(false);
        this.btSaveQuestion.setEnabled(false);
        this.btDeleteQuestion.setEnabled(false);
        this.jRadioButton1.setEnabled(false);
        this.jRadioButton2.setEnabled(false);

        this.readListSubject();
        this.loadData(listSubject);

    }

    //------------------------------------------------------------
    public void readListSubject() {
        try {
            FileInputStream file = new FileInputStream("listSubject.dat");
            ObjectInputStream read_object = new ObjectInputStream(file);
            Subject subject = new Subject();
            while ((subject = (Subject) read_object.readObject()) != null) {
                this.listSubject.add(subject);
            }
            read_object.close();
            file.close();
        } catch (IOException i) {
        } catch (ClassNotFoundException notfound) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy class");
        }
    }

    public void loadData(ArrayList<Subject> listSubject) {
        modelListSubject = new DefaultListModel();
        modelComboBox = new DefaultComboBoxModel();
        for (int i = 0; i < listSubject.size(); i++) {
            this.modelListSubject.add(i, listSubject.get(i).getCodeSubject());
            this.modelComboBox.addElement(listSubject.get(i).getCodeSubject());
            
        }
        this.jlistSubject.setModel(modelListSubject);
        this.cbSelectSubject.setModel(modelComboBox);
    }

    //--------------------------------------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistSubject = new javax.swing.JList<String>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNameSubject = new javax.swing.JTextField();
        tfCodeSubject = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taOverview = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btAddSubject = new javax.swing.JButton();
        lbThongBao = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        btDeleteSubject = new javax.swing.JButton();
        spNumberChapter = new javax.swing.JSpinner();
        lbThongBaoNameSubject = new javax.swing.JLabel();
        lbThongBaoCodeSubject = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbSelectSubject = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlistQuestion = new javax.swing.JList();
        btAddQuestion = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taNoiDungCauHoi = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlistChuong = new javax.swing.JList<Integer>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jlistAnswer = new javax.swing.JList();
        jScrollPane7 = new javax.swing.JScrollPane();
        taBarem = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbTbDienCauHoi = new javax.swing.JLabel();
        btSaveQuestion = new javax.swing.JButton();
        btDeleteQuestion = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cbDifficulty = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setFont(new java.awt.Font("Arvo", 0, 18)); // NOI18N
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Danh sách môn học");

        jlistSubject.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistSubjectValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlistSubject);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tên môn học (*):");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mã học phần (*):");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Giới thiệu môn học:");

        tfNameSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameSubjectActionPerformed(evt);
            }
        });

        taOverview.setColumns(20);
        taOverview.setRows(5);
        jScrollPane2.setViewportView(taOverview);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Số chương:");

        btAddSubject.setText("Thêm môn học");
        btAddSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddSubjectActionPerformed(evt);
            }
        });

        lbThongBao.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbThongBao.setForeground(new java.awt.Color(255, 0, 0));

        btSave.setText("Lưu");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btDeleteSubject.setForeground(new java.awt.Color(255, 0, 0));
        btDeleteSubject.setText("Xóa môn học");
        btDeleteSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteSubjectActionPerformed(evt);
            }
        });

        lbThongBaoNameSubject.setForeground(new java.awt.Color(255, 0, 0));
        lbThongBaoNameSubject.setText("Không để trống trường này");

        lbThongBaoCodeSubject.setForeground(new java.awt.Color(255, 0, 0));
        lbThongBaoCodeSubject.setText("Không để trống trường này");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btAddSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(219, 219, 219)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCodeSubject))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spNumberChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNameSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbThongBao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btDeleteSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbThongBaoNameSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbThongBaoCodeSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel3, jLabel5, jLabel6});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane2, tfCodeSubject, tfNameSubject});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbThongBao))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCodeSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbThongBaoCodeSubject)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNameSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbThongBaoNameSubject)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(spNumberChapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btAddSubject)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave)
                    .addComponent(btDeleteSubject))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel3, jLabel5});

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Subjects", jPanel5);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Chọn môn học");

        cbSelectSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectSubjectActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Danh sách câu hỏi");

        jlistQuestion.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistQuestionValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jlistQuestion);

        btAddQuestion.setText("Thêm câu hỏi");
        btAddQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddQuestionActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Trắc nghiệm");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Tự luận");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Loại câu hỏi");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nội dung câu hỏi");

        taNoiDungCauHoi.setColumns(20);
        taNoiDungCauHoi.setLineWrap(true);
        taNoiDungCauHoi.setRows(5);
        taNoiDungCauHoi.setWrapStyleWord(true);
        jScrollPane4.setViewportView(taNoiDungCauHoi);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Danh sách đáp án");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Chương");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Barem chấm điểm");

        jScrollPane5.setViewportView(jlistChuong);

        jScrollPane6.setViewportView(jlistAnswer);

        taBarem.setColumns(20);
        taBarem.setLineWrap(true);
        taBarem.setRows(5);
        taBarem.setWrapStyleWord(true);
        jScrollPane7.setViewportView(taBarem);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Thêm");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Thêm");

        lbTbDienCauHoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTbDienCauHoi.setForeground(new java.awt.Color(255, 0, 0));
        lbTbDienCauHoi.setText("Điền vào các trường bên dưới để thêm câu hỏi !");

        btSaveQuestion.setText("Lưu câu hỏi");
        btSaveQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveQuestionActionPerformed(evt);
            }
        });

        btDeleteQuestion.setForeground(new java.awt.Color(255, 51, 51));
        btDeleteQuestion.setText("Xóa câu hỏi");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Độ khó");

        cbDifficulty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dễ", "Trung Bình", "Khó" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel18))
                                .addGap(97, 97, 97)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbDifficulty, 0, 158, Short.MAX_VALUE)))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane7))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(btAddQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel8))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addGap(27, 27, 27)
                                .addComponent(cbSelectSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(lbTbDienCauHoi)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(109, 109, 109)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addGap(164, 164, 164)
                                                .addComponent(jRadioButton2)
                                                .addGap(0, 650, Short.MAX_VALUE))
                                            .addComponent(jScrollPane4)))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(459, 459, 459)
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSaveQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btDeleteQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbSelectSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbTbDienCauHoi)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btAddQuestion)
                        .addGap(0, 139, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(cbDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btSaveQuestion)
                                    .addComponent(btDeleteQuestion))))))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Question", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1534, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Exam", jPanel2);

        jLabel4.setFont(new java.awt.Font("Arvo", 0, 24)); // NOI18N
        jLabel4.setText("TEST MAKER");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameSubjectActionPerformed

    public void writeListSubject() {
        try {
            FileOutputStream file = new FileOutputStream("listSubject.dat");
            ObjectOutputStream write_object = new ObjectOutputStream(file);
            int i = 0;
            int size = this.listSubject.size();
            while (i < size) {
                Subject subject = this.listSubject.get(i);
                write_object.writeObject(subject);
                i++;
            }
            write_object.close();
            file.close();
        } catch (IOException o) {
            JOptionPane.showMessageDialog(null, "Không tạo và ghi được ra file! Lỗi");
        }
    }

    private void btAddSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddSubjectActionPerformed
        // TODO add your handling code here:
        this.btSave.setEnabled(true);
        this.tfCodeSubject.setEnabled(true);
        this.tfNameSubject.setEnabled(true);
        this.spNumberChapter.setEnabled(true);
        this.taOverview.setEnabled(true);
        this.tfNameSubject.setText("");
        this.tfCodeSubject.setText("");
        this.spNumberChapter.setValue(1);
        this.taOverview.setText("");
        this.clickAddSubject = true;
        this.lbThongBao.setText("Điền thông tin môn học mới. Các trường đánh dấu (*) không được để trống.");
        this.lbThongBao.setVisible(true);
        this.btDeleteSubject.setEnabled(false);
    }//GEN-LAST:event_btAddSubjectActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed

        Subject subject;
        String nameSubject;
        String codeSubject;
        int numberChapter;
        String overview;

        this.lbThongBaoNameSubject.setVisible(false);
        this.lbThongBaoCodeSubject.setVisible(false);
        // Nếu đã ấn vào nút Thêm môn học
        if (this.clickAddSubject) {
            nameSubject = this.tfNameSubject.getText();
            codeSubject = this.tfCodeSubject.getText();
            numberChapter = (int) this.spNumberChapter.getValue();
            overview = this.taOverview.getText();
            if (nameSubject.equals("") || codeSubject.equals("")) {
                if (nameSubject.equals("")) {
                    this.lbThongBaoNameSubject.setVisible(true);
                }
                if (codeSubject.equals("")) {
                    this.lbThongBaoCodeSubject.setVisible(true);
                }
                return;
            } else {
                subject = new Subject(nameSubject, codeSubject, numberChapter, overview);
                this.listSubject.add(subject);
                int i = this.listSubject.size() - 1;
                this.modelListSubject.add(i, listSubject.get(i).getCodeSubject());
                this.jlistSubject.setModel(modelListSubject);
                this.writeListSubject();
            }
        } else {
            Subject current = listSubject.get(this.selectedIndex);
            nameSubject = this.tfNameSubject.getText();
            codeSubject = this.tfCodeSubject.getText();
            numberChapter = (int) this.spNumberChapter.getValue();
            overview = this.taOverview.getText();
            if (nameSubject.equals("") || codeSubject.equals("")) {
                if (nameSubject.equals("")) {
                    this.lbThongBaoNameSubject.setVisible(true);
                }
                if (codeSubject.equals("")) {
                    this.lbThongBaoCodeSubject.setVisible(true);
                }
                return;
            } else {
                current.setNameSubject(this.tfNameSubject.getText());
                current.setCodeSubject(this.tfCodeSubject.getText());
                current.setNumberChapter((int) this.spNumberChapter.getValue());
                current.setOverview(this.taOverview.getText());
                this.writeListSubject();
                
                modelListSubject.remove(this.selectedIndex);
                modelListSubject.add(this.selectedIndex, this.tfCodeSubject.getText());
                this.jlistSubject.setModel(modelListSubject);
            }

        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void btDeleteSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteSubjectActionPerformed

    private void jlistSubjectValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistSubjectValueChanged
        // TODO add your handling code here:
        this.btSave.setEnabled(true);
        this.tfCodeSubject.setEnabled(true);
        this.tfNameSubject.setEnabled(true);
        this.spNumberChapter.setEnabled(true);
        this.taOverview.setEnabled(true);
        this.btDeleteSubject.setEnabled(true);
        this.lbThongBao.setText("Thay đổi thông tin môn học. Các trường đánh dấu (*) không được để trống.");
        this.lbThongBao.setVisible(true);

        String selectedMonHoc = this.jlistSubject.getSelectedValue();
        // Bắt sự kiện khi select, bỏ qua sự kiện deselect trên danh sách môn học
        if (evt.getValueIsAdjusting()) {
            for (int i = 0; i < this.listSubject.size(); i++) {
                Subject temp = listSubject.get(i);
                if (selectedMonHoc.equalsIgnoreCase(temp.getCodeSubject())) {
                    this.selectedIndex = i;
                    this.tfNameSubject.setText(temp.getNameSubject());
                    this.tfCodeSubject.setText(temp.getCodeSubject());
                    this.spNumberChapter.setValue(temp.getNumberChapter());
                    this.taOverview.setText(temp.getOverview());
                    break;
                }
            }
        }
    }//GEN-LAST:event_jlistSubjectValueChanged

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        this.loadData(listSubject);
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        this.jlistAnswer.setVisible(false);
        this.taBarem.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btAddQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddQuestionActionPerformed
        // TODO add your handling code here:
        this.lbTbDienCauHoi.setVisible(true);
        this.taBarem.setEnabled(true);
        this.taNoiDungCauHoi.setEnabled(true);
        this.jlistChuong.setVisible(true);
        this.jlistAnswer.setVisible(true);
        this.btSaveQuestion.setEnabled(true);
        this.btDeleteQuestion.setEnabled(true);
        this.jRadioButton1.setEnabled(true);
        this.jRadioButton2.setEnabled(true);
        this.jlistChuong.removeAll();
        this.jlistAnswer.removeAll();
        this.taNoiDungCauHoi.setText("");
        this.chapter = new ArrayList<>();
        
        this.modelListChapter = new DefaultListModel();
        this.modelListAnswer = new DefaultListModel();
    }//GEN-LAST:event_btAddQuestionActionPerformed

    private void jlistQuestionValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistQuestionValueChanged
        // TODO add your handling code here:
        this.subjectChoosen = this.jlistSubject.getSelectedValue();
    }//GEN-LAST:event_jlistQuestionValueChanged

    private void cbSelectSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSelectSubjectActionPerformed

    private void btSaveQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSaveQuestionActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        this.taBarem.setVisible(false);
        this.jlistAnswer.setVisible(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        AddChapter addChapter = new AddChapter(this.chapter,this.jlistChuong);
        addChapter.setVisible(true);
        
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddQuestion;
    private javax.swing.JButton btAddSubject;
    private javax.swing.JButton btDeleteQuestion;
    private javax.swing.JButton btDeleteSubject;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSaveQuestion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbDifficulty;
    private javax.swing.JComboBox cbSelectSubject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JList jlistAnswer;
    private javax.swing.JList<Integer> jlistChuong;
    private javax.swing.JList jlistQuestion;
    private javax.swing.JList<String> jlistSubject;
    private javax.swing.JLabel lbTbDienCauHoi;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JLabel lbThongBaoCodeSubject;
    private javax.swing.JLabel lbThongBaoNameSubject;
    private javax.swing.JSpinner spNumberChapter;
    private javax.swing.JTextArea taBarem;
    private javax.swing.JTextArea taNoiDungCauHoi;
    private javax.swing.JTextArea taOverview;
    private javax.swing.JTextField tfCodeSubject;
    private javax.swing.JTextField tfNameSubject;
    // End of variables declaration//GEN-END:variables
}
